[package]
name        = "carina-alpha"
description = "Carina Alpha programming language compiler"
version     = "0.0.1-dev"
authors     = ["Christian Sdunek <me@systemcluster.me>"]
publish     = false
license     = "unlicensed"

[[bin]]
name = "carina"
path = "src/main.rs"

[profile.dev]
opt-level = 0
panic = "unwind"
debug = true
debug-assertions = true

[profile.test]
opt-level = 0
debug = true
debug-assertions = true

[profile.release]
opt-level = 3
panic = "abort"
debug = false
debug-assertions = false

[dependencies]
pest = "^1"
pest_derive = "^1"
failure = "^0.1"
rand = "^0.5"
time = "^0.1"
unicode-segmentation = "^1"
simplelog = "^0.5"
log = "^0.4"
ring = "^0.13"
regex = "^1"
